#! /bin/sh

sxhkd &
picom &
~/.config/polybar/launch.sh &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
/usr/bin/lxpolkit &
flameshot &

# bspc monitor HDMI-0 -d              1
# bspc monitor DP-4   -d              2 3 4 5 6
bspc monitor -d			            1 2 3 4 5 6

bspc config border_width            3
bspc config window_gap              6

bspc config focus_follows_pointer   true
bspc config pointer_modifier	    super

bspc config split_ratio             0.50

bspc config single_monocle          true
bspc config gapless_monocle         false
bspc config paddingless_monocle     true

bspc config presel_feedback_color   "#fd2e59"

bspc config normal_border_color     "#282b30"
bspc config active_border_color     "#282b30"
bspc config focused_border_color    "#4f87c2"
